### ISSUE TITLE
Source version

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [WIITD/raylib-freebasic#10]
Hi
It may be worthwhile adding a source version to the header files?

I know this can be a bit tricky considering raylib versions are somewhat fluid.
I have been looking at something like:
Source/bi: V0.0.1
FBC: V1.09.0
raylib.h: V4.2.1.1
raygui.h: V3.2

Not sure if you plan on using revisions or snapshots at some point? I am still learning my way around github etc but would like to get a version snapshot somewhere shortly. Why? I am writing the how to guide and 3 books of examples based on the current versions in C, Py3 and FB  so just attempting to keep the lib versions API the same across all 3 :)

**Comment by WIITD** [comment]
in raylib.bi and raygui.bi there already is #define RAYLIB_VERSION and #define RAYGUI_VERSION, i might be good to make release tag on github for every major release

**Comment by Axle-Ozz-i-sofT** [comment]
Sorry, I was thinking more of the record of previous updates releases.
I am attempting to keep versions matched across C, FB and Py atm.
raylib releases have outdated examples so I have had to look at the current examples which some are updated to v4.2.
But trying to stay with raylib v4,2,0 and raygui v3.2.0
So I am collecting releases and versions and changes and archiving them all atm lol
But maybe just setting a release of your headers as a source archive. I think I have a copy of your earlier v4.0 headers somewhere.

I am new to github, so still feeling my way around atm.

**Comment by WIITD** [comment]
i don't see any point for making release tag for every minor update.
i will make a release before updating to newer version of raylib, but every update to 4.2 branch is just a bugfix so i shouldn't break the api.
i'm not sure if i can make release tag  of previous versions, but it's possible to check commit history and get back to 4.0 and 3.7 to get a copy

**Comment by Axle-Ozz-i-sofT** [comment]
Sounds good. I'm a noob with GutHub, so trying to get my head around organizing myself :)

Thanks :)

P.S. I added the models_geometric_shapes.bas into my repo.
https://github.com/Axle-Ozz-i-sofT/A-BEGINNERS-GUIDE-TO-PROGRAMMING/tree/main/3_Libraries_Overview/Tests_source/raylib/FreeBASIC
