### ISSUE TITLE
raygui support

### ISSUE THREAD

**Issue by funlw65** [WIITD/raylib-freebasic#2]
There is a method to include raygui. h in raylib to have only one library. You have to rename raygui.h to raygui.c and copy it in the raylib folder, and then deliver some specific options to Makefile (or directly edit the Makefile). 

Anyway, this preparation of raylib library is the user's job, what we need is the raygui header only (no need to code also the functions).

Thank you!

**Comment by Axle-Ozz-i-sofT** [comment]
Hi,
I would like to second the above. I am in need of the raygui 3.1 as a separate .bi or included in the raylib in place of the older \src\extra\raygui.h

I have been looking into how to convert the C source to FB .bi, but so far it has appeared a little confusing.

**Comment by WIITD** [comment]
with update to raylib 4.2 i have created bindings to raygui 3.2
