### ISSUE TITLE
header has illegal specifications due to using freebasic keywords as variable names 

### ISSUE THREAD

**Issue by NighthowlerStudios** [WIITD/raylib-freebasic#3]
D:\coding\FreeBASIC\brokeengine\BrokeEngine\lib\raylib-freebasic-main\raylib.bi(189) error 59: Illegal specification, at parameter 3 (width) of constructor stdcall(as single, as single) in 'constructor Rectangle(x as single, y as single, width as single, height as single)'

**Comment by NighthowlerStudios** [comment]
This is because Width is actually a keyword reserved for the freebasic language, and freebasic syntax is not entirely case sensitive.  I recommend changing the names of such variables

**Comment by NighthowlerStudios** [comment]
you have also used left, right, color, name, point, ptr and data in this manner

**Comment by WIITD** [comment]
i paid attention to catch every illegal specification while updating to 4.2
