### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by glowiak2** [WIITD/raylib-freebasic#5]
/usr/home/glowiak/src/vala/raylib-freebasic-main/raylib.bi(189) error 59: Illegal specification, at parameter 3 (width) of constructor(as single, as single) in 'constructor Rectangle(x as single, y as single, width as single, height as single)'

**Comment by WIITD** [comment]
this should now be fixed

**Comment by c-sanchez** [comment]
https://www.freebasic.net/forum/viewtopic.php?p=292991#p292991
Maybe is related?
